spring:
  profiles:
    active: local

---
spring:
  profiles: local

  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
  h2:
    console:
      path: /h2console
      enabled: true
      settings:
        web-allow-others: true
